"""Texas hold'em game logic

Docs: https://galopyz.github.io/holdem/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['suits', 'ranks', 'Card', 'c1', 'rank_values', 'get_ranks_counts', 'is_flush', 'is_straight', 'evaluate_hand',
           'compare_hands', 'hand_name', 'mk_deck', 'shuffle_deck', 'withdraw_card', 'equity', 'Action', 'human',
           'always_call', 'always_check', 'always_fold', 'always_raise', 'Player', 'ActionHandler', 'Stage', 'Round',
           'act', 'Game']

# %% ../nbs/00_core.ipynb #7e7fcc2f
from fastcore.utils import *
from fastcore.test import *

import random
from collections import namedtuple, Counter
from enum import Enum, auto
from dataclasses import dataclass, field
from typing import Callable

# %% ../nbs/00_core.ipynb #d454a188
suits = '♠♥♦♣'
suits

# %% ../nbs/00_core.ipynb #5cb6417a
ranks = '2,3,4,5,6,7,8,9,10,J,Q,K,A'.split(',')
ranks

# %% ../nbs/00_core.ipynb #efd4de99
Card = namedtuple('Card', ['suit', 'rank'])

c1 = Card('♠', '10')
c1.suit, c1.rank

# %% ../nbs/00_core.ipynb #39963143
@patch
def __repr__(self: Card): return self.suit + self.rank

# %% ../nbs/00_core.ipynb #0448dcd6
rank_values = {r:i for i,r in enumerate(ranks, start=2)}
rank_values

# %% ../nbs/00_core.ipynb #5aaaac81
@patch
def __lt__(self: Card, other: Card): return rank_values[self.rank] < rank_values[other.rank]

# %% ../nbs/00_core.ipynb #bc7e8414
@patch
def __eq__(self: Card, other: Card): return rank_values[self.rank] == rank_values[other.rank]

# %% ../nbs/00_core.ipynb #309effa9
# limited: Works with `L[arg]`, but loses the parameter info inside L. Use `types.GenericAlias`
@patch
def __class_getitem__(cls: L, *item): return cls

# %% ../nbs/00_core.ipynb #7c487938
def get_ranks_counts(cards: list[Card]) -> L[tuple[int, ...], tuple[int, ...]]:
    """Return ((ranks...), (counts...)) sorted by count then by rank value from cards"""
    items = Counter(rank_values[c.rank] for c in cards).items()
    return L(*sorted(items, key=itemgetter(1, 0), reverse=True)).zip()

# %% ../nbs/00_core.ipynb #eb53774f
def is_flush(cards: list[Card]) -> list:
    "If cards have flush, return the `rank_values` from the cards in sorted order. If not, return []"
    suit, count = Counter(c.suit for c in cards).most_common(1)[0]
    return sorted([c for c in cards if c.suit == suit], reverse=True) if count >= 5 else []

# %% ../nbs/00_core.ipynb #d8bb12dd
def is_straight(cards: list[Card]) -> int:
    "Return the highest value of the straight if cards contain 5 consecutive ranks, else 0"
    vals = sorted({rank_values[c.rank] for c in cards}, reverse=True)
    if 14 in vals: vals.append(1)
    for i in range(len(vals) - 4):
        if vals[i] - vals[i+4] == 4: return vals[i]
    return 0

# %% ../nbs/00_core.ipynb #47a69a69
def evaluate_hand(cards: list[Card]) -> tuple:
    """Return hand rank tuple for the best 5-card hand from `cards`.
    Hands ranked from 1 (high card) to 10 (royal flush). Each rank tuple
    starts with the hand category, followed by tiebreaker values (kickers
    or relevant ranks)."""
    ranks, counts = get_ranks_counts(cards)
    c0, c1, *rest = counts
    straight_val = is_straight(cards)
    flush_cards = is_flush(cards)
    sf_val = is_straight(flush_cards)
    if sf_val == 14: return (10,) # royal flush
    elif sf_val: return (9, sf_val) # straight flush
    elif c0 == 4: return (8, ranks[0], ranks[1]) # four of a kind
    elif c0 == 3 and c1 >= 2: return (7, ranks[0], ranks[1]) # full house
    elif flush_cards: return (6, *(rank_values[c.rank] for c in flush_cards)) # flush
    elif straight_val: return (5, straight_val) # straight
    elif c0 == 3: return (4, ranks[0], ranks[1], ranks[2]) # three of a kind
    elif c0 == 2 and c1 == 2: return (3, ranks[0], ranks[1], ranks[2]) # two pair
    elif c0 == 2: return (2, ranks[0], ranks[1], ranks[2], ranks[3]) # one pair
    else: return (1, *ranks) # high card

# %% ../nbs/00_core.ipynb #3f496872
def compare_hands(hands: list[list[Card]]) -> tuple:
    """Return the winning hand rank among `hands`."""
    return max(evaluate_hand(h) for h in hands)

# %% ../nbs/00_core.ipynb #491fa4c1
_RANK = {2:'two',3:'three',4:'four',5:'five',6:'six',7:'seven',8:'eight',9:'nine',
         10:'ten',11:'jack',12:'queen',13:'king',14:'ace'}
_HAND = {10:'royal flush',9:'straight flush',8:'four of a kind',7:'full house',
         6:'flush',5:'straight',4:'three of a kind',3:'two pair',2:'one pair',1:'high card'}

# %% ../nbs/00_core.ipynb #5388aad4
def hand_name(rank: tuple) -> str:
    "Readable name for an `evaluate_hand` tuple, e.g. (7,3,2) -> 'full house, threes over twos'."
    cat, vals = rank[0], rank[1:]
    name = _HAND[cat]
    if cat == 10: return name
    if cat in (9, 5): return f"{name}, {_RANK[vals[0]]}-high"
    if cat in (8, 4): return f"{name}, {_RANK[vals[0]]}s"
    if cat == 7: return f"{name}, {_RANK[vals[0]]}s over {_RANK[vals[1]]}s"
    if cat == 6: return f"{name}, {_RANK[vals[0]]}-high"
    if cat == 3: return f"{name}, {_RANK[vals[0]]}s and {_RANK[vals[1]]}s"
    if cat == 2: return f"{name}, {_RANK[vals[0]]}s"
    return f"{name}, {_RANK[vals[0]]}-high"

# %% ../nbs/00_core.ipynb #b01df9a4
def mk_deck(suits: list = suits, ranks: list = ranks) -> L:
    "Create a deck with given suits and ranks"
    return L(Card(s,r) for s in suits for r in ranks)

# %% ../nbs/00_core.ipynb #a4351f26
def shuffle_deck(deck: list[Card]) -> list[Card]:
    "Shuffle `deck` in place and return it"
    random.shuffle(deck)
    return deck

# %% ../nbs/00_core.ipynb #47529f84
def withdraw_card(deck: list[Card], n: int=1) -> list[Card]:
    "Withdraw `n` cards from `deck` and return them. Modifies `deck` in place."
    if len(deck) < n: raise ValueError(f"Not enough cards: asked for {n}, only {len(deck)} left")
    return [deck.pop() for _ in range(n)]

# %% ../nbs/00_core.ipynb #3331caea
def equity(hand: list[Card], community: list[Card] = (), n_opponents: int = 1,
           n_sims: int = 10_000, seed: int = None) -> dict:
    """Monte Carlo estimate of win/tie/lose fractions for `hand` given `community` vs `n_opponents`. 
    Pass `seed` for reproducible classroom demos."""
    if n_opponents < 1: raise ValueError('n_opponents must be >= 1')
    hand, community = list(hand), list(community)
    known = set(hand) | set(community)
    deck = [c for c in mk_deck() if c not in known]
    rng = random.Random(seed)
    wins = ties = 0
    fill = 5 - len(community)
    for _ in range(n_sims):
        rng.shuffle(deck)
        n_opp = 2*n_opponents
        board = community + deck[n_opp : n_opp+fill]
        mine = evaluate_hand(hand + board)
        best = max(evaluate_hand(deck[2*j:2*j+2] + board) for j in range(n_opponents))
        if mine > best: wins += 1
        elif mine == best: ties += 1
    return {'win': wins/n_sims, 'tie': ties/n_sims, 'lose': 1-(wins+ties)/n_sims}

# %% ../nbs/00_core.ipynb #a0320337
class Action(Enum):
    RAISE = auto()
    CALL = auto()
    CHECK = auto()
    FOLD = auto()

# %% ../nbs/00_core.ipynb #1f3ca451
def human(): 
    while True:
        act, *amnt = input("Choose your action. Type 'call', 'check', 'fold', 'raise X' with X to raise the bet.").split()
        if (action := getattr(Action, act.upper(), None)): return (action, int(*amnt) if amnt else 0)
        print(f"Invalid action: {act}. Try again.")

# %% ../nbs/00_core.ipynb #91a68457
def always_call(): return (Action.CALL, 0)

def always_check(): return (Action.CHECK, 0)

def always_fold(): return (Action.FOLD, 0)

def always_raise(n):
    def _raise(): return (Action.RAISE, n)
    _raise.__name__ = f'always_raise({n})'
    return _raise

# %% ../nbs/00_core.ipynb #ba4c98b5
@dataclass
class Player:
    username: str = 'new_user' # username
    balance: int = 0 # total balance
    bet: int = 0 # active bet this round
    playing: bool = True # playing this round or not
    hand: list = field(default_factory=list) # playing hand
    strategy: Callable = always_call # a strategy the player uses to make actions (human or ai)

    def perform_action(self, stage_bet) -> int: return ActionHandler(self, stage_bet).handle()
    
    def reset_bet(self): self.bet = 0

    def reset_playing(self): self.playing = True
    
    def call(self, need): return self._place_bet(need)

    def check(self): return 0

    def fold(self): self.playing = False; return 0

    def raise_(self, need): return self._place_bet(need)
    
    def _place_bet(self, amt):
        self.balance -= amt
        self.bet += amt
        return amt

# %% ../nbs/00_core.ipynb #246c624a
class ActionHandler:
    def __init__(self, player, stage_bet):
        self.player = player
        self.stage_bet = stage_bet
    
    def handle(self):
        action, amount = self.player.strategy()
        print(f'{self.player.username} intends to {action.name.lower()}, stage_bet: {self.stage_bet}, raise_amount: {amount}')
        return getattr(self, '_'+action.name.lower())(amount)

    def _call(self, amount):
        need = self.stage_bet - self.player.bet
        if self.player.balance < need:
            if self.player.strategy != human: return self.player.fold() # AI folds when not enough balance for now..
            print(f"Cannot call. balance ({self.player.balance}) too low to match the stage_bet ({self.stage_bet}). Current bet: {self.player.bet}")
            return self.handle()
        else:
            return self.player.call(need)

    def _check(self, amount): return self.player.check()

    def _fold(self, amount): return self.player.fold()

    def _raise(self, amount):
        new_stage_bet = self.stage_bet + amount
        need = new_stage_bet - self.player.bet
        if need > self.player.balance:
            if self.player.strategy != human: return self.player.fold() # AI folds when not enough balance for now..
            print(f'Cannot raise by {amount}. Your balance: {self.player.balance}, current bet: {self.player.bet}, stage_bet: {self.stage_bet}')
            return self.handle()
        else:
            return self.player.raise_(need)

# %% ../nbs/00_core.ipynb #feadc3ec
class Stage(Enum):
    PREFLOP = auto()
    FLOP = auto()
    TURN = auto()
    RIVER = auto()

# %% ../nbs/00_core.ipynb #dd91f808
class Round:
    def __init__(self, players = None, deck = None, community = None, stage = Stage.PREFLOP, stage_bet = 0, pot = 0):
        self.players = [] if players is None else players
        self.deck = shuffle_deck(mk_deck()) if deck is None else deck
        self.community = [] if community is None else community
        self.stage = stage
        self.stage_bet = stage_bet
        self.pot = pot
        self._idx = 0
        self._raiser = -1
    
    def state(self):
        "Return a string describing the current game situation."
        if self.stage is None: return "Game is over"
        player = self.players[self._idx]
        return f"{player.username}'s turn | Stage: {self.stage.name} | Hand: {player.hand} | Community: {self.community} | Stage bet: {self.stage_bet} | Your bet: {player.bet} | Balance: {player.balance} | Pot: {self.pot}"

# %% ../nbs/00_core.ipynb #161cd548
@patch
def _distribute(self: Round, winners) -> None:
    "Distribute the prize pot to the winners"
    print(f"Distributing $ {self.pot} to {winners}")
    for player in winners: player.balance += self.pot // len(winners)

# %% ../nbs/00_core.ipynb #2459b50d
@patch
def _prep_round(self: Round):
    "Prepare for the round by getting the deck, shuffle, deal hole hands."
    self.deck = shuffle_deck(mk_deck())
    for p in self.players: 
        p.reset_playing()
        p.hand = withdraw_card(self.deck, 2)
    self.community = []
    self.pot = 0
    self.stage = Stage.PREFLOP

# %% ../nbs/00_core.ipynb #35cc9d59
@patch
def _reset_betting_round(self: Round):
    "Reset state for a new betting round."
    self._raiser, self.stage_bet, self._idx = -1, 0, 0
    for p in self.players: p.reset_bet()

# %% ../nbs/00_core.ipynb #4c280abc
@patch
def _deal_community(self: Round):
    "Deal community cards"
    if self.stage == Stage.FLOP: 
        self.community += withdraw_card(self.deck, 3)
    elif self.stage in (Stage.TURN, Stage.RIVER): 
        self.community += withdraw_card(self.deck)
    print(f"\n--- {self.stage.name} --- Community: {self.community}")

# %% ../nbs/00_core.ipynb #6e0532c8
@patch
def _get_next_player(self: Round) -> Player:
    while True:
        player = self.players[self._idx]
        if player.playing:
            if player.strategy is human:
                bet_amt = yield player
            else:
                bet_amt = player.perform_action(self.stage_bet)
            self.pot += bet_amt
            if player.bet > self.stage_bet:
                self._raiser = self._idx
                self.stage_bet = player.bet
        self._idx = (self._idx + 1) % len(self.players)
        if self._raiser == -1: self._raiser = 0
        if self._idx == self._raiser: break

# %% ../nbs/00_core.ipynb #e1133205
@patch
def _showdown(self: Round):
    "Evaluate and distribute."
    players = L.filter(attrgetter('playing'))(self.players)
    winning_score = compare_hands([p.hand + self.community for p in players])
    winners = [p for p in players if evaluate_hand(p.hand + self.community) == winning_score]
    print(f"Winners: {[p.username for p in winners]} with {winning_score}")
    self._distribute(winners)

# %% ../nbs/00_core.ipynb #cfe46e08
@patch
def start_round(self: Round):
    "Deal, start PREFLOP, and auto-advance to first human player."
    self._prep_round()
    self._reset_betting_round()
    for s in Stage:
        self.stage = s
        self._deal_community()
        self._reset_betting_round()
        yield from self._get_next_player()
    self.stage = None
    self._showdown()

# %% ../nbs/00_core.ipynb #9611714e
def act(game, player, round):
    if player is None: print("Game is over"); return
    try:
        player = game.send(player.perform_action(round.stage_bet))
    except StopIteration:
        player = None
    return player

# %% ../nbs/00_core.ipynb #11a8cb5f
class Game:
    def __init__(self, players):
        self.players = players
        self._round = None
        self._gen = None
        self.current = None  # human to act; None = hand over

    def start(self):
        "Deal a fresh hand and advance to the first human turn."
        self._round = Round(players=self.players)
        self._gen = self._round.start_round()
        self.current = next(self._gen, None)
        print(self.state())

    def act(self):
        "Play one human turn (AI turns auto-play inside the generator)."
        if self.current is None: return
        try:
            self.current = self._gen.send(self.current.perform_action(self._round.stage_bet))
        except StopIteration:
            self.current = None
        print(self.state())

    def state(self): return self._round.state() if self._round else "Game is over"
