# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/holdem',
                'doc_host': 'https://galopyz.github.io',
                'git_url': 'https://github.com/galopyz/holdem',
                'lib_path': 'holdem'},
  'syms': {'holdem.core': {'holdem.core.foo': ('core.html#foo', 'holdem/core.py')}}}
