"""Fill in a module description here

Docs: https://galopyz.github.io/holdem/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['suits', 'ranks', 'Card', 'rank_values', 'get_ranks_counts', 'is_flush', 'is_straight', 'evaluate_hand',
           'compare_hands', 'shuffle_deck', 'withdraw_card', 'Action', 'human', 'always_call', 'Player',
           'ActionHandler', 'Stage', 'Round', 'act']

# %% ../nbs/00_core.ipynb #7e7fcc2f
from fastcore.utils import *
from collections import namedtuple
from collections import Counter
import random
from enum import Enum, auto
from dataclasses import dataclass, field

# %% ../nbs/00_core.ipynb #d454a188
suits = '♠♥♦♣'
suits

# %% ../nbs/00_core.ipynb #5cb6417a
ranks = '2,3,4,5,6,7,8,9,10,J,Q,K,A'.split(',')
ranks

# %% ../nbs/00_core.ipynb #efd4de99
Card = namedtuple('Card', ['suit', 'rank'])
Card

# %% ../nbs/00_core.ipynb #39963143
@patch
def __repr__(self: Card): return self.suit + self.rank

# %% ../nbs/00_core.ipynb #0448dcd6
rank_values = {r:i for i,r in enumerate(ranks, start=2)}
rank_values

# %% ../nbs/00_core.ipynb #5aaaac81
@patch
def __lt__(self: Card, other: Card): return rank_values[self.rank] < rank_values[other.rank]

# %% ../nbs/00_core.ipynb #bc7e8414
@patch
def __eq__(self: Card, other: Card): return rank_values[self.rank] == rank_values[other.rank]

# %% ../nbs/00_core.ipynb #09923ede
def get_ranks_counts(cards: list[Card]) -> tuple[tuple[int, ...], tuple[int, ...]]:
    """Return ((ranks...), (counts...)) sorted by count then by rank value from cards"""
    items = Counter([rank_values[c.rank] for c in cards]).items()
    return tuple(zip(*sorted(items, key=lambda o: (o[1], o[0]), reverse=True)))

# %% ../nbs/00_core.ipynb #8c97737d
def is_flush(cards: list[Card]) -> list:
    "If cards have flush, return the `rank_values` from the cards in sorted order. If not, return []"
    suit, count = Counter(c.suit for c in cards).most_common()[0]
    if count >= 5:
        return sorted([rank_values[c.rank] for c in cards if c.suit == suit][:5], reverse=True)
    return []

# %% ../nbs/00_core.ipynb #be23e19d
def is_straight(cards: list[Card]) -> int:
    "Return the highest value of the straight if cards contain 5 consecutive ranks, else 0"
    vals = sorted([rank_values[c.rank] for c in cards], reverse=True)
    if vals[0] == 14: 
        vals.append(1)
    for i in range(len(vals) - 4):
        if vals[i] - vals[i+4] == 4 and len(set(vals[i:i+5])) == 5:
            return vals[i]
    return 0

# %% ../nbs/00_core.ipynb #47a69a69
def evaluate_hand(cards: list[Card]) -> tuple:
    """Return hand rank tuple for the best 5-card hand from `cards`.
    Hands ranked from 1 (high card) to 10 (royal flush). Each rank tuple
    starts with the hand category, followed by tiebreaker values (kickers
    or relevant ranks).
    """
    ranks, counts = get_ranks_counts(cards)
    straight_val = is_straight(cards)
    flush_vals = is_flush(cards)
    if straight_val == 14: # royal flush
        return (10,)
    elif straight_val != 0 and flush_vals != []: # straight flush
        return (9, straight_val)
    elif counts[0] == 4: # four of a kind
        return (8, ranks[0], ranks[1])
    elif counts[0] == 3 and counts[1] >= 2: # full house
        return (7, ranks[0], ranks[1])
    elif flush_vals != []: # flush
        return (6, *flush_vals)
    elif straight_val != 0: # straight
        return (5, straight_val)
    elif counts[0] == 3: # three of a kind
        return (4, ranks[0], ranks[1], ranks[2])
    elif counts[0] == 2 and counts[1] == 2: # two pair
        return (3, ranks[0], ranks[1], ranks[2])
    elif counts[0] == 2: # one pair
        return (2, ranks[0], ranks[1], ranks[2], ranks[3])
    else: # high card
        return (1, *ranks)

# %% ../nbs/00_core.ipynb #3f496872
def compare_hands(hands: list[list[Card]]) -> tuple:
    """Return the winning hand rank among `hands`."""
    return sorted([evaluate_hand(h) for h in hands], reverse=True)[0]

# %% ../nbs/00_core.ipynb #a4351f26
def shuffle_deck(deck: list[Card]) -> list[Card]:
    "Shuffle `deck` in place and return it"
    random.shuffle(deck)
    return deck

# %% ../nbs/00_core.ipynb #47529f84
def withdraw_card(deck: list[Card], n: int=1) -> list[Card]:
    "Withdraw `n` cards from `deck` and return them. Modifies `deck` in place."
    return [deck.pop() for _ in range(n)]

# %% ../nbs/00_core.ipynb #a0320337
class Action(Enum):
    RAISE = auto()
    CALL = auto()
    CHECK = auto()
    FOLD = auto()

# %% ../nbs/00_core.ipynb #1f3ca451
def human(player): 
    prompt = f"""This is {player.username}'s turn! Type an action: Call, Check, Fold, Raise X with X amount
     your current bet: {player.bet}, your hand: {player.hand}"""
    while True:
        act, *amnt = input(prompt).split()
        if (action := getattr(Action, act.upper(), None)):
            return (action, int(*amnt) if amnt else 0)
        print(f"Invalid action: {act}. Try again.")

# %% ../nbs/00_core.ipynb #91a68457
def always_call(player): return (Action.CALL, 0)

# %% ../nbs/00_core.ipynb #2e0471ff
@dataclass
class Player:
    username: str = 'new_user' # username
    balance: int = 0 # total balance
    bet: int = 0 # active bet this round
    playing: bool = True # playing this round or not
    hand: list = field(default_factory=list) # playing hand
    strategy: callable = always_call # a strategy the player uses to make actions (human or ai)

    def perform_action(self, stage_bet) -> tuple[Action, int, int]:
        ah = ActionHandler(self, stage_bet)
        return ah.handle()

# %% ../nbs/00_core.ipynb #cdf4b940
class ActionHandler:
    def __init__(self, player, stage_bet):
        self.player = player
        self.stage_bet = stage_bet
    
    def handle(self):
        action, amount = self.player.strategy(self.player)
        print(f'{self.player.username} intends to {action.name.lower()}, stage_bet: {self.stage_bet}, raise_amount: {amount}')
        return getattr(self, '_'+action.name.lower())(amount)

    def _call(self, amount):
        need = self.stage_bet - self.player.bet
        if self.player.balance < need:
            print(f"Cannot call. balance ({self.player.balance}) too low to match the stage_bet ({self.stage_bet}). Current bet: {self.player.bet}")
            return self.handle()
        else:
            self.player.balance -= need
            self.player.bet += need
            return need

    def _check(self, amount): return 0

    def _fold(self, amount):
        self.player.playing = False
        return 0

    def _raise(self, amount):
        new_stage_bet = self.stage_bet + amount
        need = new_stage_bet - self.player.bet
        if need > self.player.balance:
            print(f'Cannot raise by {amount}. Your balance: {self.player.balance}, current bet: {self.player.bet}, stage_bet: {self.stage_bet}')
            return self.handle()
        else:
            self.player.balance -= need
            self.player.bet += need
            return need

# %% ../nbs/00_core.ipynb #feadc3ec
class Stage(Enum):
    PREFLOP = auto()
    FLOP = auto()
    TURN = auto()
    RIVER = auto()

    def next(self):
        """Return the next stage, or None if already at RIVER."""
        return Stage(self.value + 1) if self.value < len(Stage) else None

# %% ../nbs/00_core.ipynb #dd91f808
class Round:
    def __init__(self, players = None, deck = None, community = None, stage = Stage.PREFLOP, stage_bet = 0, pot = 0):
        self.players = [] if players is None else players
        self.deck = shuffle_deck([Card(s,r) for s in suits for r in ranks]) if deck is None else deck
        self.community = [] if community is None else community
        self.stage = stage
        self.stage_bet = stage_bet
        self.pot = pot
    
    def state(self):
        "Return a string describing the current game situation."
        if self.stage is None: return "Game is over"
        player = self.players[self._idx]
        return f"{player.username}'s turn | Stage: {self.stage.name} | Hand: {player.hand} | \
        Community: {self.community} | Stage bet: {self.stage_bet} | Your bet: {player.bet} | Balance: {player.balance} | Pot: {self.pot}"

# %% ../nbs/00_core.ipynb #161cd548
@patch
def _distribute(self: Round, winners) -> None:
    "Distribute the prize pot to the winners"
    print(f"Distributing $ {self.pot} to {winners}")
    for player in winners:
        player.balance += self.pot // len(winners)

# %% ../nbs/00_core.ipynb #2459b50d
@patch
def _prep_round(self: Round):
    "Prepare for the round by getting the deck, shuffle, deal hole hands."
    self.deck = shuffle_deck([Card(s,r) for s in suits for r in ranks])
    for p in self.players: 
        p.playing = True
        p.hand = withdraw_card(self.deck, 2)
    self.community = []
    self.pot = 0
    self.stage = Stage.PREFLOP

# %% ../nbs/00_core.ipynb #35cc9d59
@patch
def _reset_betting_round(self: Round):
    "Reset state for a new betting round."
    self._raiser, self.stage_bet, self._idx = -1, 0, 0
    for p in self.players: p.bet = 0

# %% ../nbs/00_core.ipynb #4c280abc
@patch
def _deal_community(self: Round):
    "Deal community cards"
    if self.stage == Stage.FLOP: 
        self.community += withdraw_card(self.deck, 3)
    elif self.stage in (Stage.TURN, Stage.RIVER): 
        self.community += withdraw_card(self.deck)
    print(f"\n--- {self.stage.name} --- Community: {self.community}")

# %% ../nbs/00_core.ipynb #6e0532c8
@patch
def _get_next_player(self: Round) -> Player:
    while True:
        player = self.players[self._idx]
        if player.playing:
            if player.strategy is human:
                bet_amt = yield player
            else:
                bet_amt = player.perform_action(self.stage_bet)
            self.pot += bet_amt
            if player.bet > self.stage_bet:
                self._raiser = self._idx
                self.stage_bet = player.bet
        self._idx = (self._idx + 1) % len(self.players)
        if self._raiser == -1: self._raiser = 0
        if self._idx == self._raiser: break

# %% ../nbs/00_core.ipynb #e1133205
@patch
def _showdown(self: Round):
    "Evaluate and distribute."
    winning_score = compare_hands([p.hand + self.community for p in self.players if p.playing])
    winners = [p for p in self.players if evaluate_hand(p.hand + self.community) == winning_score]
    print(f"Winners: {[p.username for p in winners]} with {winning_score}")
    self._distribute(winners)

# %% ../nbs/00_core.ipynb #cfe46e08
@patch
def start_round(self: Round):
    "Deal, start PREFLOP, and auto-advance to first human player."
    self._prep_round()
    self._reset_betting_round()
    for s in Stage:
        self.stage = s
        self._deal_community()
        self._reset_betting_round()
        yield from self._get_next_player()
    self.stage = None
    self._showdown()

# %% ../nbs/00_core.ipynb #9611714e
def act(game, player, round):
    if player is None: print("Game is over"); return
    try:
        player = game.send(player.perform_action(round.stage_bet))
    except StopIteration:
        player = None
    return player
