"""Fill in a module description here

Docs: https://galopyz.github.io/holdemcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #705d3c49
def foo(): pass
